version: '3'

services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
    - MYSQL_ROOT_PASSWORD=tyrell
    - MYSQL_DATABASE=tyrell
    - MYSQL_USER=tyrell
    - MYSQL_PASSWORD=tyrell
  php:
    image: tyrell_php
    restart: always
    depends_on:
    - mysql
    volumes:
    - ./server/entry.sh:/script/entry.sh
    - ./server/php.ini:/usr/local/etc/php/php.ini
    - ./server/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
    - DBSERVER=mysql
    command: /script/entry.sh
  web:
    image: nginx:alpine
    depends_on:
    - php
    volumes:
    - ./server/default.conf:/etc/nginx/conf.d/default.conf
